### Función que inicia sesión, recibe un parametro email y un password
POST http://localhost:3000/admin/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "123"
}

### Función que cierra sesión y elimina el token del usuario. recibe el token por header
GET http://localhost:3000/admin/logout
Authorization: b1056d1769a940a9acacfc622a72f92e0a861da2bb55438db495b48374c5376b

### Función que actualiza el token de usuario y deja obsoleta las anteriores credenciales
GET http://localhost:3000/admin/token
Authorization: ce3714b71cef4a2faa24c82d60c95bd6039e64f31c6e435fad9cbb019085a536

